// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxDBSnxAhxmHVSGb2EYOzqAlELDk0Eq1s',
    appId: '1:102226961719:web:37e7a65d3c500aeaa0a6b2',
    messagingSenderId: '102226961719',
    projectId: 'mibookreview',
    authDomain: 'mibookreview.firebaseapp.com',
    storageBucket: 'mibookreview.firebasestorage.app',
    measurementId: 'G-TN92FNFQE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNhOwJFChoBAoJh68oTY74ZSBgGSc7Dc',
    appId: '1:102226961719:android:4625f9cc511086c6a0a6b2',
    messagingSenderId: '102226961719',
    projectId: 'mibookreview',
    storageBucket: 'mibookreview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm1JACbF_wV3gJHVjBM8-aue3WHu60GNw',
    appId: '1:102226961719:ios:7838f12e93cc39e1a0a6b2',
    messagingSenderId: '102226961719',
    projectId: 'mibookreview',
    storageBucket: 'mibookreview.firebasestorage.app',
    iosBundleId: 'com.example.bookReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm1JACbF_wV3gJHVjBM8-aue3WHu60GNw',
    appId: '1:102226961719:ios:7838f12e93cc39e1a0a6b2',
    messagingSenderId: '102226961719',
    projectId: 'mibookreview',
    storageBucket: 'mibookreview.firebasestorage.app',
    iosBundleId: 'com.example.bookReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxDBSnxAhxmHVSGb2EYOzqAlELDk0Eq1s',
    appId: '1:102226961719:web:0a7cd4e6d8e21b69a0a6b2',
    messagingSenderId: '102226961719',
    projectId: 'mibookreview',
    authDomain: 'mibookreview.firebaseapp.com',
    storageBucket: 'mibookreview.firebasestorage.app',
    measurementId: 'G-QL95S6R00C',
  );
}
